### ISSUE TITLE
Bug with 16CF0000 style windows

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltDrag#226]
When the option is set to "move window" on left mouse button on title bar:
![NQZ82zN7yn](https://user-images.githubusercontent.com/47380919/180436908-54380903-2a23-4eaa-b9ec-5279d2cb27b5.png)

There is a bug which affects only 16CF0000 style windows
(eg. notepad++ and Anlink):
![AltSnap_p7knPdrZPM](https://user-images.githubusercontent.com/47380919/180437030-c40d6e1a-185f-4fff-9d30-2db431103812.png)

You can only click the top half of the minimize button to minimize the window,
If you click on the bottom half of the minimize window it either glitches or maximizes the window:

https://user-images.githubusercontent.com/47380919/180437401-bcbdcfd7-8f74-43cf-9f9e-1f264a575b55.mp4

**Comment by RamonUnch** [comment]
This is a windows bug, there is not much I can do about this outside of disabling titlebar actions all together
See this post https://github.com/RamonUnch/AltSnap/issues/83#issuecomment-917953420 for more details

**Comment by RamonUnch** [comment]
Actually it is not really possible.
AltSnap only interacts with windows movement for a reason, one of them is Alt+Click, an other is titlebar click.
In this latter case AltSnap detects via a WM_NCHITTEST message that the click was performed in a titlebar and performs the titlebar action instead of letting windows handle the click.
The way to go would be to improve titlebar detection with an additional heuristic in addition to the WM_NCHITTEST message. this could lead to other bugs however. I am still invistigating for a better solution.
