### ISSUE TITLE
Missing feature from Stefan Sundin's version

### ISSUE THREAD

**Issue by brian6932** [RamonUnch/AltDrag#24]
So I just found about this fork and it's pretty neat, but I noticed a missing feature. Stefan Sundin's version had a feature in which if you had a window activated with AltDrag and pressed right click while having left click held it would maximize the selected window.

**Comment by RamonUnch** [comment]
Yes I did remove this feature because it was annoying to me and it was a mess in the code.
To maximize/minimize a window you need to Alt+DBClick, you can also configure a middle mouse button or scroll wheel as to the Maximize option.
Do you want this feature back?

**Comment by brian6932** [comment]
I used it quite a lot, After submitting the issue post I went through the ini's and noticed that it was removed, I find using right click a lot faster than alt double click.

Also, one other thing that caught me off guard was that `RefreshRate` was very low at first, I think that a value of 7hz is a very low default.

Original ini:
`AutoRemaximize=1`
`; Automatically re-maximize windows when you move them between monitors.`
`; List of settings:`
`; 0: Disabled.`
`; 1: Enabled.`
`; 2: Enabled, but restore window after one second.`
`; You can press the right mouse button (resize action) when moving a window to toggle maximized state.`
Fork ini:
`AutoRemaximize=1`
`; Automatically re-maximize windows when you move them between monitors.`

**Comment by RamonUnch** [comment]
RefreshRate is in ms not in Hz, 7ms is actualy 142Hz which is much more that most people need.
If you put a higher value you will have a slower refresh rate!

I will add back this option for next release.

**Comment by brian6932** [comment]
Oh my bad, weirdly enough it felt sluggish for me, I guess I'm used to 165Hz at this point, setting it to 0 fixed that for me though

**Comment by RamonUnch** [comment]
If you want the most reactivity put MoveRate=1 and RefreshRate=0
But I recommend to keep RefreshRate at 7 ms because AltDrag can otherwise eat crazy amount of CPU trying to refresh a window up to thousands of time per second depending on your config if your mouse has a high frequency.

I chosed 7ms very deliberately because it corresponds to the double frequency of most 60Hz monitors meaning it will save CPU without ever showing any bagginess. The only case you would need a frequency higher than 140 Hz is if you have a 100Hz+ monitor. So again I recomend to keep the default value unless you have high frequency monitor.

**Comment by brian6932** [comment]
Yea as I mentioned I use a 165Hz monitor, I set it to the minimum latency settings, If I do notice a problem, I'll def tweak it more, I have a pretty beefy cpu

**Comment by RamonUnch** [comment]
For a 165 Hz monitor it is true that 0 is a good value.
The AutoRemaximize option was indeed changed as well. There is a remaining bug that makes it non working on the latest 1.35. Use the hooks.dll from https://github.com/RamonUnch/AltDrag/issues/22#issuecomment-770348207 if you want a debugged version.

**Comment by brian6932** [comment]
I also found a typo in the ini on line 15
`; Horizontal ans vertical position (from top left in percent) where the aero`
ans should be and

**Comment by RamonUnch** [comment]
Thanks for the typo, I do a lot of them and English is not my native language.
Have a try with this AltDrag.exe/Hooks.dll combo.

This is optional but enabled by default.
To disable it use: MMMaximize=0 in the [General] section of your AltDrag.ini

[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5912231/AltDrag.zip)

**Comment by brian6932** [comment]
Yea it works, nice

**Comment by RamonUnch** [comment]
Note that the main feature I removed from original AltDrag is the HookWindow that I do not plan on re-implementing.
Note2: In this case the window is not restored when pressing left-right click, just maximized, do you think it should restore a maximized window too?

I think that with the original altdrag a single Alt+LClick was restoring a maximized window. with this release you have to drag the window if it is snapped or maximized in order to restore it. which I think is sufficient?

You have for now a pre-release, so you have extra options, have a look at this AltDrag.ini to see what's new. if you want to play around...
You have a new "Roll/Unroll" action, you can restore a snapped window with normal mouse movement and you can set a max speed beyond which AltDrag will no longer try to snap windows.
[AltDragini.zip](https://github.com/RamonUnch/AltDrag/files/5912437/AltDragini.zip)

**Comment by brian6932** [comment]
Ah I see what you mean
>In this case the window is not restored when pressing left-right click, just maximized, do you think it should restore a maximized window too?
I think it should, it feels pretty weird that you can't
>I think that with the original altdrag a single Alt+LClick was restoring a maximized window. with this release you have to drag the window if it is snapped or maximized in order to restore it. which I think is sufficient?
I feel like the way it's currently implemented feels sluggish, the click feels a lot snappier than a drag

**Comment by RamonUnch** [comment]
> I feel like the way it's currently implemented feels sluggish, the click feels a lot snappier than a drag

I prefer the way it is and it took me quite some work to properly write. The original altdrag was restoring always when I did not want it to and this is the main reason I started writing this version (it was also a common issue I saw other people complain about). I think the older behavior makes less sense given that normal window snapping (window 7+) does requires to move the mouse in order to restore a snapped/maximized window, same for most Linux windows managers.

However for sure implementing the toggle is trivial, here it is: Now maximized window will be restored when left-right clicking.
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5912700/hooks.zip)

**Comment by brian6932** [comment]
Yea that feels better, however, this only addresses the left click, the right click doesn't toggle, and for me that is even more useful than the left click toggle. Also, correct me if I'm wrong, but you could just make toggling options in the ini right? That way you can have both options, I do see and understand both use cases.

**Comment by RamonUnch** [comment]
You mean that when resizing, you would like the left button to toggle min/max?

**Comment by RamonUnch** [comment]
I can actually restore on a simple click with associated option as you suggest.
Just set 
MMMaximize=3
; Set the way MouseMove can maximize default is 1.
; Set to 1 to maximize/restore on left+right click.
; Set to 2 to restore on a SINGLE left click.
; set to 3 for both.
; set to 0 to disable any of those.

I think I understand what you mean, with my version you cannot hold LClick and loop through max/restore. now you can...
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5913300/hooks.zip)

**Comment by brian6932** [comment]
>Just set
MMMaximize=3

I don't have this variable in the ini file you sent me, should I just add it to a section? If so which?

**Comment by RamonUnch** [comment]
add it to the [General] section.
It is the same parameter than mentioned above...

**Comment by brian6932** [comment]
Ok so there's a weird bug with right click activating 2x sometimes, I made sure to check with the Stefan Sundin's version and that didn't exhibit this behavior

**Comment by RamonUnch** [comment]
The window will be restoren when your mouse moves, I will fix that

**Comment by RamonUnch** [comment]
Try this one.
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5913842/hooks.zip)

**Comment by brian6932** [comment]
A little buggy, but it works well, not sure how it happened but it broke my explorer so I had to restart it

**Comment by RamonUnch** [comment]
If this happens again, inform me, this is quite strange

**Comment by RamonUnch** [comment]
This feature is now present in latest 1.36
