### ISSUE TITLE
Title bar blacklist?

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltDrag#246]
Is is possible to exclude windows from the titlebar actions?
The windows store for example is on the `Windows Blacklist` but the titlebar action still works on it.

**Comment by RamonUnch** [comment]
it is `MMBLower` blacklist:

```
In the [Blacklist] section

MMBLower=*|CASCADIA_HOSTING_WINDOW_CLASS,*|SDL_app,*|MozillaDialogClass
; List of windows for which the Titlebar action should not be performed.
; default is MS-WindowTerminal and all SDL programs.
```

**Comment by RamonUnch** [comment]
Maybe have a quick look at the wiki it should contain details about most advanced settings.

**Comment by RamonUnch** [comment]
If you the program you are blacklisting should be blacklisted for all users then it can be added to the default blacklist and benefit future users.

**Comment by RamonUnch** [comment]
Interesting, however I expect Windows 11 store to have the `*|ApplicationFrameWindow` class, so unless we blacklist the exe name, it would not be language neutra or we would have to blacklist all windows applications. So I am not sure it should be done.

**Comment by Ichisich** [comment]
Yes, the store is in the `*|ApplicationFrameWindo` class.
Unfortunately, many UWP applications use interface elements implemented in their title bar nowadays.

Store has a search bar, Photos and Movies a backwards handle etc.

@rp1231 
Instead of blacklisting you can search either with Ctrl+F or, and that works with every title bar, hold the modifier key to disable title bar actions temporary.

**Comment by RamonUnch** [comment]
I see indeed, I will link this issue to the wiki. I will not include it by default, because it would not be language neutral and it would not be desired by everyone, plus by default the titlebar actions are not enabled so it is not a huge deal. thanks for your insights both of you.
