### ISSUE TITLE
More of a question (about blacklists and scroll action)

### ISSUE THREAD

**Issue by brian6932** [RamonUnch/AltDrag#25]
So I use alt + scroll a lot in Photoshop, is there a way to whitelist Photoshop?
Identify window shows this: `Adobe Photoshop 2021|Photoshop`

**Comment by RamonUnch** [comment]
I am not sure I understand. If you want the Scroll action from AltDrag, then do not blacklist the program, otherwise add it to the windows blacklist. add a coma without spaces before or after the coma followed by 
Adobe Photoshop 2021|Photoshop
The space is have to be present in the middle of the name or class.
Windows in the "Window blacklist" will be ignored by AltDrag for almost any kind of action,
An other way is to add Photoshop.exe to the process blacklist. again no spaces before or after coma.

What do you mean by whitelist exactly?

**Comment by RamonUnch** [comment]
Ok I reviewed my code and actually several Scroll actions ignore the blacklist.
I will fix that and probably add a Scroll blacklist that will allow to disable just the scroll action in case it is needed.

**Comment by RamonUnch** [comment]
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5936643/AltDrag.zip)
Try this combo AltDrag+hooks.dll
It no longer ignores the Windows blacklist for all scroll actions.
It also adds the Scroll field in the [Blacklist] section of AltDrag.ini
I replaced in the GUI the Snaplist with this Scroll blacklist. I think the Snapllist is quite advanced and can be left to the .ini edition only.

So go in the config in blacklist and add *|Photoshop in the 
'Windows that should ignore scroll action:' list.

**Comment by RamonUnch** [comment]
Also I would suggest to use only the Win key as a hotkey if you have several programs where you use Alt+Click or Alt+Scroll.
This will minimize the blacklist nightmare and maximize the number of programs you can use AltDrag with.

**Comment by brian6932** [comment]
Yea that worked, thank you

**Comment by RamonUnch** [comment]
FYI
The version I posted however applies the window blacklist to all scroll actions, however The next release will actually separate the scroll blacklist from the window blacklist.
* The window will disable all "click actions" such as move/resize
* The Scroll blacklist will only disable the scroll action.
* The process blacklist will apply to both.

This means that if you use Alt+Tab scroll action for example and want to do Alt+Tab action when a scroll-blacklisted window is maximized then you still can use it by pointing the cursor to the taskbar. Same for the Volume action.
