### ISSUE TITLE
Keep settings when updating?

### ISSUE THREAD

**Issue by FSund** [RamonUnch/AltDrag#3]
Just updated to the 1.32, and noticed my .ini-file was overwritten. Perhaps this is a requirement while there are big changes being made to the application.

**Comment by RamonUnch** [comment]
I agree it would be nice to have migration process for the ini.
If everything went fine the old ini file should be there as well, named "AltDrag-old.ini"
You can delete the new ini and restore the old one. It should always work.
Probably I will modify the installer so that it no longer overrides the config, but instead adds "altdrag-new.ini" as a reference for latest config options.
Even without an ini file AltDrag will load fine,  However all default blacklists will be empty and there will be no comments in the ini file.
At the beginning I was making more changes to the ini that is why I preferred to overwrite it.

**Comment by RamonUnch** [comment]
From 1.33 It will keep settings
