### ISSUE TITLE
Roll/Unroll windows - Lower windows by middle clicking - Scroll wheel + Volume

### ISSUE THREAD

**Issue by muvrini** [RamonUnch/AltDrag#33]
First of all, thank you for your great developement 

I noticed ...
-	Roll/Unroll windows: A rolled up window cannot be unrolled after Altdrag has been deactivated or closed and then reactivated or restarted.
-	Lower windows by middle clicking cannot be disabled - it always (!) continues to work, even after closing Altdrag. It would also be good if you could extend the function with Ctrl/Win/Alt - I always close tabs in Firefox by middle clicking. 
-	Scroll wheel + Volume does not work on the desktop (only there).

W10-20H2

Greeting from Bonn!

**Comment by RamonUnch** [comment]
> Roll/Unroll windows: A rolled up window cannot be unrolled after Altdrag has been deactivated or closed and then reactivated or restarted.

This will not be fixed because the restoring parameters are stored by AltDrag and are forgotten when restarting or enabling/disabling AltDrag. Trying to save them would be a mess and lead to a ton of potential bugs, just do not restart AltDrag all the time, if you want to be able to restore windows. Note that this is the same fro Snapped windows.

> Lower windows by middle clicking cannot be disabled - it always (!) continues to work, even after closing Altdrag. It would also be good if you could extend the function with Ctrl/Win/Alt - I always close tabs in Firefox by middle clicking.

Very strange, are you sure you are using the latest AltDrag? Could you check that another instance of AltDrag is not running?
For me whichever is the windows version (Win10/8/1/XP) I cannot reproduce this problem and I myself do not use it.
Under Firefox When this option the tabs are closed (because tabs are not a titlebar outside of some buggy apps), I do not know what you are doing. If needed You can add *|MozillaWindowClass in the MMBLower blacklist (in the ini file).

> Scroll wheel + Volume does not work on the desktop (only there).

This is normal as the Desktop is in the default Scroll blacklist, just remove "Program Manager|Progman fom" the Scroll blacklist, if you want the scroll action to work on the desktop. (actually this is the only action for which it makes sense).

I will consider adding the Lower with Alt+MMB on titlebar instead of just MMB as an option. it makes sence especially because of the Roll.Unroll option...

**Comment by RamonUnch** [comment]
1) Keep in mind that you can always unroll manually a window (it is just resized to very flat).
2) to edit the AltDrag.ini file for advanced configuration, middle click on the tray icon.
If you still have problems with the midle click lower option send me your AltDrag.ini file and check if you have other programs that filter the keyboard/mouse input, such as AutoHotkey, maybe they are interaction and I can fix it once I can reproduce.

**Comment by muvrini** [comment]
Roll/Unroll windows - it's ok for me, I often change the windows-size with shortcuts ... 
Lower windows - your thoughts are good, i forgot the AutoHotkey - and here is also the conflict. After ending AutoHotkey, AltDrag works fine. 
The Blacklist - I'm blind, this is the solution. 
Middle click to reach the advanced configuration ist very convenient!

**Comment by RamonUnch** [comment]
It is actually not that obvious, I would need to work on a wiki or a good help file but it would take as much time as writing the program. There is very basing Getting started information in AltDrag.txt in AltDrag's folder, but it is incomplete and not detailed.

The original AltDrag documentation is quite good and remains mostly relevant. It had the advantage to have fewer blacklists which was more clear, but less powerful.

Here in the attached version you can set with the ini file, LowerWithMMB=2 instead of 1 and you will lower only on Alt+MMB on the titlebar.

[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6092920/AltDrag.zip)

**Comment by muvrini** [comment]
Merci! I think the explanations in the ini file are already good. So far they have always helped me (okay, sometimes I'm blind too ...). However, AltDrag is already a very granular program at this point. In order to recognize its full functionality, you have to deal quite intensively. Something the "normal" user will not always be willing to do. In this respect, I think the differentiation between the settings in the window and the advanced settings via the ini file is very good So everyone should be able to cope with it. In the long run, an easily understandable help would certainly be appropriate. It would also help a wider distribution. 

LowerWithMMB = 2 (Alt + MMB) works very well. But! LowerWithMMB = 1 (MMB) works just as well. The difference is only the opening of a new tab, which by lowering, is omitted. Both options are equally appealing.

**Comment by RamonUnch** [comment]
in v1.39

**Comment by muvrini** [comment]
v1.39 - No function on LowerWithMMB=2, 1+3 works

**Comment by muvrini** [comment]
Sorry for the confusion, I didn't look closely - everything is fine!
