### ISSUE TITLE
Bug: Need to press ctrl after very desktop unlock

### ISSUE THREAD

**Issue by SonGokussj4** [RamonUnch/AltDrag#46]
Hi, firstly let me tell you - big thanks for continuing AltDrag. There were some problems with the original version that you resolved in this and it's awesome!

Found a bug. 

When I lock my screen `[WIN+L]`, and unlock it by pin, the cursor is behaving somewhat weirdly. It can't click on windows, it's like there is pushed a button all the time.

I need to press `[CTRL]` to "unhook" this and now the cursor behaves and works normally.

If I disable AltDrag this is not happening.

**Comment by RamonUnch** [comment]
Add L to the Killkeys in the [Input] section of AltDrag.ini
alternatively i guess that if you run AltDrag elevated you will not have the problem.
Use the virtual key hex code '4C' for 'L'
Killkeys=09 4C

09 is here for TAB already.
The reason is that AltDrag is not informed of the Win UP event because you are logged off.
The keys in the Killkeys list will disable altdrag when pressed down.

**Comment by RamonUnch** [comment]
Use: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
For a list of all the codes...

**Comment by SonGokussj4** [comment]
Resolved. Changed `Killkeys=09` to `Killkeys=09 4C` 

I had to restart AltDrag for it to work.

I any case, thank you, a little FAQ or readme help would be great for this because I don't belive I'm the only one to lock computer and have `LWIN` as AltDrag shortcut :-) 

Thanks again.

**Comment by RamonUnch** [comment]
I will add the L key in the default Killkeys.
I would love to have more time to write a FAQ, but it would take as much time as writing the program itself.
You can read the AltDrag.txt file for some basic documentation. I will try to update it better.

**Comment by RamonUnch** [comment]
Should be fixed with v1.42
