### ISSUE TITLE
Blacklist: Blacklist Move and not Resize

### ISSUE THREAD

**Issue by mdroidian** [RamonUnch/AltDrag#65]
Is it possible to blacklist `move` and not `resize` via Directly editing AltDrag.ini?

As in, one could still Alt+Right Click, but could not Alt+Left Click.

**Comment by RamonUnch** [comment]
It is not possible for now to blacklist move and resize separately.
I do not see an application.. Maybe you have a specific idea?
If you want not to be able to resize windows that *should* not be resized, you can uncheck the **Resize all windows** options.

**Comment by RamonUnch** [comment]
If you have interaction problems with Alt+click being used by some programs, I suggest you try to use the WinKey instead of Alt, or even a Key combo.
You can use Win+Alt+Right click to resize and Win+Right click to move, or any other key combo.
I try not to have too many blacklists even hidden in the AltDrag.ini

**Comment by mdroidian** [comment]
> Maybe you have a specific idea?
> If you have interaction problems with Alt+click being used by some programs
Yes, just this.  Alt+Click with Todoist.

But the suggestion with `Win+Right Click` I think will do the trick!  I'm not sure why I had `Alt` stuck in my head.

Thank you kindly!
