### ISSUE TITLE
Snapping to borderless window and Horizontal Scroll problems

### ISSUE THREAD

**Issue by Nostaljaded** [RamonUnch/AltDrag#68]
To reproduce:
_Either_ launch 2 Window Explorer/File Explorer windows
* `Toggle borderless` for 1 window with AltDrag
* Try snapping the bordered window to the borderless

_Or_ run `mpv` media player with `no-border` option
* Play a low resolution video file
* Try snapping a Window Explorer/File Explorer window to mpv

`AllSnap` (program no longer maintained though) is able to snap window to mpv with `no-border` option.
Tested on Win7 with AltDrag v1.43.

_P.S. Many thanks on improving AltDrag._ :)

**Comment by RamonUnch** [comment]
This is a voluntary behavior, because in the genral case a window that has no borders should not be snapped to special popups and such).
If you want to snap to a specific Window that has no borders, then you want to add it to the Snaplist in the [Blacklist] section of the AltDrag.ini (middle click the tray icon to open the ini file). I suggest you add the mpv window to the list.

If you want to enable snapping on all borderless windows you can set `Snaplist=*|*`.

**Comment by Nostaljaded** [comment]
Sweet!

**Comment by Nostaljaded** [comment]
Another issue I'm experiencing is unable to scroll horizontally in Firefox/GIMP by `holding shift`.
No issue in Chromium by `holding shift` OR with a mouse that has a tilt-able wheel (hardware horizontal scrolling) to scroll horizontally in Firefox/GIMP.

To reproduce:
* Go to Yahoo website in a small Firefox window OR
* Zoom in on an image in GIMP
(both can use portable version if not installed)

Let me know if it's better to open a new issue instead.

**Comment by RamonUnch** [comment]
Strange, I will check this more in detail, could you check if you have the same problem with the Original AltDrag 1.1?
I think I did not modify the scroll inactive window option in the end.

**Comment by RamonUnch** [comment]
PS: Did you try also to disable AltDrag and then to scroll with Shift + hardware horizontal scrolling, maybe some programs want Shift NOT to be pressed for the scroll, because Indeed AltDrag forwards the the key state.

**Comment by RamonUnch** [comment]
Actually this is the problem, It seems that Firefox detects if the Shift key is pressed and ignores all scroll events when it is the case.

I am not sure what to do about this, because I cannot prevent Shift from being pressed down, otherwise Shift would always be unusable...

I think the best solution would be to let the user select which key he wants to enable Horizontal Scroll, this also would make a way to disable it.

Try with this version of AltDrag and set:
```
in the [Input] section of AltDrag.ini
HScrollKey=XX
; Key used to transform a vertical scroll in Horizontal scroll
; Applies only when the InactiveScroll option is used
; Default value is 10 ie VK_SHIFT.
```
You could put one of the Xbuttons of your mouse for example 05 or 06
Or even 04 (middle click, so that Middleclick+Scroll => Hscroll
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6641851/AltDrag.zip)

**Comment by Nostaljaded** [comment]
_FYI:_ Using vanilla v1.43, `shift + hardware horizontal scrolling` becomes 'Goes back one page' & 'Goes forward one page' in reverse direction for Firefox.
With just hardware horizontal scrolling, horizontal scrolling will work on inactive window with AltDrag.

Coming back to the above modified AltDrag files, software horizontal scrolling works but it **will make the window active** and **still execute Firefox original functions** after releasing `HScrollKey` if using the below suggested mouse buttons:
* MB4 & MB5 'Goes back one page' & 'Goes forward one page' respectively;
* using `MMB` if cursor over a hyperlink, opens link in a new tab

So I'm using `Caps Lock` key in the meantime.
Thank you!

Would it be possible to implement it as an option in this dropdown menu too?
![1](https://user-images.githubusercontent.com/28423237/121774849-547a7380-cb52-11eb-9b00-1883f2ed65ca.png)

**Comment by RamonUnch** [comment]
What option would you like in this? I am not sure I understand.
The HScrollKey option concerns the **Scroll inactive window** option, not the Scroll action, that is applied when ALT is down.

I could add a drop-list to select the HScrollKey, but I would like to avoid this because there are already many options and Scroll inactive windows cannot be implemented by AltDrag on Windows 10 which is the main version used among my users.
So all the Scroll inactive code Is kept (because I do care about older windows versions) but I prefer to keep this "advanced" setting to the .ini file only.

**Comment by Nostaljaded** [comment]
Not asking to add a drop-list to select the HScrollKey.

Yes, **I'm requesting to also add a `horizontal scrolling` option for the Scroll action when ALT is down (_only if_ it doesn't clash and works in Win10 as well)**.
As currently only `Caps Lock` key for HScrollKey is feasible as other keys are either not working, result in undesired behaviors or too far away from the left hand natural resting position.

> Highlighting here if not aware:
> The combination of `InactiveScroll=1` & `HScrollKey` actually also enables mice without hardware horizontal scrolling to do horizontal scrolling even for active Firefox window.
> There are many mice that does not have the tilt wheel, e.g. 14 out of 26 Logitech mice in their current catalog.
> 
> This (unintended?) effect makes using those mice do horizontal scrolling in Firefox become such an ease.

So if adding a `horizontal scrolling` option for the Scroll action when ALT is down is doable, it will be more intuitive (for me) to use `Alt` instead of `Caps Lock`.
Of course HScrollkey should still be available as others might prefer another key to be down instead.

**Comment by RamonUnch** [comment]
This is a good idea actually.
It would not work on metro apps on windows 10 but would not break anything.
I will see to implement this.

**Comment by RamonUnch** [comment]
Well that was very simple, have a try with this one.
[AltDrag-1.44-test9.zip](https://github.com/RamonUnch/AltDrag/files/6642633/AltDrag-1.44-test9.zip)

The problem however is not really solved because some other programs may want to interpret a scroll action differently when Alt is pressed. so now it works for Firefox but not for MailNews (interlink). 
This option can be used with or without scroll inactive windows option.

**Comment by Nostaljaded** [comment]
> The problem however is not really solved because some other programs may want to interpret a scroll action differently when Alt is pressed. so now it works for Firefox but not for MailNews (interlink).

I'm actually using `WIN` down key, so it's less of an issue. My assumption with `WIN` key is most programs will have less (if not zero) interactions with `WIN` key.

> This option can be used with or without scroll inactive windows option.

On test 10, I can still do horizontal scrolling on inactive window (both Firefox & Chromium), even when unchecking scroll inactive windows option; vertical scrolling is working as expected.
