### ISSUE TITLE
Elevate on Autostart not working

### ISSUE THREAD

**Issue by squabbi** [RamonUnch/AltDrag#81]
Version 1.45, Windows 21H1.

I've tried toggling the settings for auto starting AltDrag when logging on, as well as the option to elevate to administrator privileges. I still have to open the configuration panel and press 'Elevate' upon startup.

I have UAC prompts disabled on my system.

Are there any logs or other troubleshooting steps I should take?

**Comment by RamonUnch** [comment]
Try setting `AlwaysElevate=1` in the `[Advanced]` section of AltDrag.ini.
To open AltDrag.ini, just middleclick on the tray Icon.

**Comment by RamonUnch** [comment]
I think I got the problem.
Use this version of AltDrag.exe
If it does not fix the problem, then try the `AltDragLog.exe` and copy/paste the content of the ad.log file after a reboot.
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6797316/AltDrag.zip)

**Comment by squabbi** [comment]
Perfect! It works as intended now! Thank you very much. :)

I didn't need to make any changes to AltDrag.ini, upon rebooting with the version attached above AltDrag elevated itself successfully. The configuration file still has the option for `AlwaysElevate` as `0` (even after toggling the option) - is that the intended function/behaviour?

**Comment by RamonUnch** [comment]
The elevate to administrator priviledge only applies to the startup by adding the `-elevate` command line aprameter to altdrag command.
You can see it in the registery :
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`
in the `AltDrag`key
The `AlwaysElevate` option can only be set manually in the ini and will force altdrag to ask for elevation.

The problem was that the command line parameter was ignored because of a bug I introduced while modifying the code.

**Comment by RamonUnch** [comment]
Fixed in 1.46
